name: Build and deploy a docker image on push

on:
  push:
    branches: 
      - 'release/**'
    paths-ignore:
    - '**.yml'
    - 'README.md'
    
jobs:
  
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/${{github.repository}}/rainier:latest
    - name: Push Docker Image  
      run: docker push docker.pkg.github.com/${{github.repository}}/rainier:latest


