name: Build And Deploy Docker Image to Repo

on:
  push:
    paths-ignore:
    - '**.yml'
    - 'README.md'
    
jobs:
  
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: phyteclabs/si
        tags: latest


