name: Build and deploy a docker image on push

on:
  push:
    branches: 
      - 'release/**'
    paths-ignore:
    - '**.yml'
    - 'README.md'
    
jobs:
  
  build:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: phyteclabs/rainier
          tags: latest


